version: "3.9"

services:
  dash:
    image: shreeyxkta/ml-car-price:latest
    platform: linux/x86_64
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "9001:80"
    volumes:
      - ./app:/root/app
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80
    command: python /root/app/app.py
