services:
  dash:
    image: shreeyxkta/ml-car-price:latest
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./app:/root/app
       - ./model:/root/app/model
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=8050
    command: python /root/app/app.py
